"""`slurm-monitor bootstrap`: build the agent environment on the cluster.

One `ssh host bash -s` invocation runs a generated bash script fed on stdin (each ssh round trip
costs a ~7 s login shell, so everything happens in a single call). The script embeds a base64
tar.gz of the installed slurm_monitor package, and:

  1. finds uv (PATH, then ~/.local/bin/uv, else installs it);
  2. exits 0 early when $AGENT_DIR exists and --force was not given;
  3. builds everything in $AGENT_DIR.tmp: `uv venv`, `uv pip install` of the agent requirements
     with CC=gcc SLURM_INCLUDE_DIR=/usr/include SLURM_LIB_DIR=/usr/lib64 (overridable from the
     remote environment), unpacks slurm_monitor into site-packages, compiles slurm_monitor_ext;
  4. verifies the import and `python -m slurm_monitor.agent --check`, writes manifest.json;
  5. moves $AGENT_DIR.tmp to $AGENT_DIR. A trap removes $AGENT_DIR.tmp on any failure, so a
     broken build never leaves a partial environment behind.

With host=None the same script runs through a local `bash -s`. Nothing here is invoked by the
TUI path; bootstrap is only ever explicit.
"""

from __future__ import annotations

import base64
import io
import shlex
import subprocess
import sys
import tarfile
import threading
import time
from collections import deque
from importlib import metadata
from pathlib import Path, PurePosixPath
from typing import IO

import slurm_monitor
from slurm_monitor.config import Resolved

DISTRIBUTION = "slurm-monitor"
# Used when the distribution metadata is unavailable (running from an unpacked source tree).
FALLBACK_REQUIREMENTS = ("pydantic>=2.7", "pyslurm==25.11.2", "cython>=3.0", "setuptools>=70")
STDERR_TAIL_LINES = 40
# Package contents that must not ship to the cluster: caches, locally built artifacts, tests.
EXCLUDED_PARTS = frozenset({"__pycache__", "build", "tests"})
EXCLUDED_SUFFIXES = frozenset({".pyc", ".pyo", ".so", ".c", ".egg-info"})


def agent_requirements() -> list[str]:
    """pydantic plus the `agent` extra (pyslurm pin, cython, setuptools) from pyproject metadata."""
    try:
        requires = metadata.requires(DISTRIBUTION) or []
    except metadata.PackageNotFoundError:
        return list(FALLBACK_REQUIREMENTS)
    base: list[str] = []
    agent: list[str] = []
    for req in requires:
        spec, _, marker = req.partition(";")
        spec = spec.strip()
        marker = marker.replace("'", '"')
        if not marker and spec.startswith("pydantic"):
            base.append(spec)
        elif 'extra == "agent"' in marker:
            agent.append(spec)
    return base + agent if agent else list(FALLBACK_REQUIREMENTS)


def package_tarball(root: Path | None = None) -> bytes:
    """tar.gz of the slurm_monitor package as `slurm_monitor/...`, without caches or binaries."""
    root = Path(slurm_monitor.__file__).parent if root is None else root
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w:gz") as tar:
        for path in sorted(root.rglob("*")):
            rel = path.relative_to(root)
            if not path.is_file():
                continue
            if EXCLUDED_PARTS & set(rel.parts[:-1]) or path.suffix in EXCLUDED_SUFFIXES:
                continue
            tar.add(path, arcname=str(PurePosixPath("slurm_monitor") / rel.as_posix()))
    return buf.getvalue()


def render_script(settings: Resolved, force: bool, tarball: bytes | None = None) -> str:
    """The bash script `bash -s` executes on the target host."""
    tarball = package_tarball() if tarball is None else tarball
    b64 = base64.encodebytes(tarball).decode("ascii").rstrip("\n")
    reqs = " ".join(shlex.quote(r) for r in agent_requirements())
    return SCRIPT_TEMPLATE.format(
        agent_dir=shlex.quote(settings.cluster.agent_dir),
        python=shlex.quote(settings.cluster.python),
        force="1" if force else "0",
        reqs=reqs,
        b64=b64,
    )


# Braces are doubled for str.format; ${{var}} in the template is ${var} in the script.
SCRIPT_TEMPLATE = r"""#!/usr/bin/env bash
# Generated by `slurm-monitor bootstrap`; executed with `bash -s` on the target host.
set -euo pipefail

AGENT_DIR={agent_dir}
AGENT_DIR="${{AGENT_DIR/#\~/$HOME}}"
TMP="$AGENT_DIR.tmp"
FORCE={force}
PYTHON_VERSION={python}
export CC="${{CC:-gcc}}"
export SLURM_INCLUDE_DIR="${{SLURM_INCLUDE_DIR:-/usr/include}}"
export SLURM_LIB_DIR="${{SLURM_LIB_DIR:-/usr/lib64}}"

log() {{ printf 'bootstrap: %s\n' "$*" >&2; }}

# Any failure removes the partial build; $AGENT_DIR itself is only touched at the very end.
cleanup() {{
  local rc=$?
  if [ "$rc" -ne 0 ]; then
    log "FAILED (exit $rc); removing $TMP"
    rm -rf "$TMP"
  fi
}}
trap cleanup EXIT

if [ -e "$AGENT_DIR" ] && [ "$FORCE" -eq 0 ]; then
  log "already bootstrapped at $AGENT_DIR (pass --force to rebuild)"
  if [ -f "$AGENT_DIR/manifest.json" ]; then cat "$AGENT_DIR/manifest.json"; echo; fi
  exit 0
fi

UV="$(command -v uv || true)"
if [ -z "$UV" ] && [ -x "$HOME/.local/bin/uv" ]; then UV="$HOME/.local/bin/uv"; fi
if [ -z "$UV" ]; then
  log "uv not found; installing to ~/.local/bin"
  curl -LsSf https://astral.sh/uv/install.sh | sh >&2
  UV="$HOME/.local/bin/uv"
fi
log "using $UV"

rm -rf "$TMP"
mkdir -p "$TMP"
log "creating venv with python $PYTHON_VERSION in $TMP/venv"
"$UV" venv --python "$PYTHON_VERSION" "$TMP/venv" >&2
PY="$TMP/venv/bin/python"

log "installing {reqs}"
log "build env: CC=$CC SLURM_INCLUDE_DIR=$SLURM_INCLUDE_DIR SLURM_LIB_DIR=$SLURM_LIB_DIR"
"$UV" pip install --python "$PY" {reqs} >&2

SITE="$("$PY" -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])')"
log "unpacking slurm_monitor into $SITE"
rm -rf "$SITE/slurm_monitor"
DECODE='import base64, sys; sys.stdout.buffer.write(base64.b64decode(sys.stdin.read()))'
"$PY" -c "$DECODE" <<'SLURM_MONITOR_TARBALL' | tar -xzf - -C "$SITE"
{b64}
SLURM_MONITOR_TARBALL

log "compiling slurm_monitor_ext"
(cd "$SITE/slurm_monitor/ext" && "$PY" setup.py build_ext --build-lib "$SITE" >&2)
rm -rf "$SITE/slurm_monitor/ext/build" "$SITE/slurm_monitor/ext/"*.egg-info

log "verifying extension import"
"$PY" - >&2 <<'PYEOF'
import pyslurm, slurm_monitor_ext
built = ".".join(map(str, slurm_monitor_ext.extension_version()))
print(f"slurm_monitor_ext built against Slurm {{built}}, pyslurm {{pyslurm.__version__}}")
PYEOF
log "verifying agent handshake"
"$PY" -m slurm_monitor.agent --check > "$TMP/handshake.json"
cat "$TMP/handshake.json" >&2

"$PY" - "$TMP" <<'PYEOF'
import datetime, json, sys
import slurm_monitor
tmp = sys.argv[1]
with open(f"{{tmp}}/handshake.json") as f:
    hs = json.load(f)
manifest = {{
    "slurm_monitor_version": slurm_monitor.__version__,
    "pyslurm_version": hs["pyslurm_version"],
    "slurm_built_version": hs["slurm_built_version"],
    "slurm_running_version": hs["slurm_running_version"],
    "extension_available": hs["extension_available"],
    "python": sys.version.split()[0],
    "created_at": datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds"),
}}
with open(f"{{tmp}}/manifest.json", "w") as f:
    json.dump(manifest, f, indent=2)
PYEOF

if [ -e "$AGENT_DIR" ]; then
  log "replacing existing $AGENT_DIR"
  rm -rf "$AGENT_DIR"
fi
mv "$TMP" "$AGENT_DIR"
log "ready: $AGENT_DIR"
cat "$AGENT_DIR/manifest.json"
echo
"""


def bootstrap_command(settings: Resolved) -> list[str]:
    """`bash -s` locally, or over ssh with the cluster's ssh options (never -t)."""
    host = settings.cluster.host
    if host is None:
        return ["bash", "-s"]
    return ["ssh", *settings.cluster.ssh_options, host, "bash -s"]


def agent_python(agent_dir: str) -> str:
    """Remote interpreter path; a leading ~ is left for the remote shell to expand."""
    return f"{agent_dir.rstrip('/')}/venv/bin/python"


def remote_agent_command(settings: Resolved) -> list[str]:
    """argv the SSH transport runs. When the venv is missing the remote shell exits 127 with
    `bash: ~/.slurm-monitor/venv/bin/python: No such file or directory`, which the transport
    maps to BootstrapRequired."""
    host = settings.cluster.host
    if host is None:
        raise ValueError("remote_agent_command needs a cluster with a host")
    return [
        "ssh",
        *settings.cluster.ssh_options,
        host,
        f"{agent_python(settings.cluster.agent_dir)} -m slurm_monitor.agent",
    ]


def local_agent_available(agent_dir: str) -> bool:
    return (Path(agent_dir).expanduser() / "venv" / "bin" / "python").exists()


def run_script(
    command: list[str],
    script: str,
    stdout: IO[str] | None = None,
    stderr: IO[str] | None = None,
) -> tuple[int, list[str]]:
    """Feed `script` to `command` on stdin; stream its stdout/stderr live and keep a stderr tail."""
    out = sys.stdout if stdout is None else stdout
    err = sys.stderr if stderr is None else stderr
    tail: deque[str] = deque(maxlen=STDERR_TAIL_LINES)

    def pump(src: IO[str], dst: IO[str], keep: deque[str] | None) -> None:
        for line in src:
            dst.write(line)
            dst.flush()
            if keep is not None:
                keep.append(line.rstrip("\n"))

    proc = subprocess.Popen(
        command,
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        bufsize=1,
    )
    assert proc.stdin and proc.stdout and proc.stderr
    threads = [
        threading.Thread(target=pump, args=(proc.stdout, out, None), daemon=True),
        threading.Thread(target=pump, args=(proc.stderr, err, tail), daemon=True),
    ]
    for t in threads:
        t.start()
    try:
        proc.stdin.write(script)
        proc.stdin.close()
    except BrokenPipeError:
        pass  # the remote side died before reading the script; the exit code says why
    rc = proc.wait()
    for t in threads:
        t.join()
    return rc, list(tail)


def run_bootstrap(settings: Resolved, force: bool) -> int:
    target = settings.cluster.host or "localhost"
    agent_dir = settings.cluster.agent_dir
    command = bootstrap_command(settings)
    print(
        f"slurm-monitor bootstrap: preparing {agent_dir} on {target} "
        f"({' '.join(shlex.quote(c) for c in command)})",
        file=sys.stderr,
    )
    started = time.monotonic()
    rc, tail = run_script(command, render_script(settings, force))
    elapsed = time.monotonic() - started
    if rc != 0:
        print(
            f"slurm-monitor bootstrap: failed on {target} (exit {rc}, {elapsed:.0f}s); "
            f"last {min(len(tail), 15)} stderr lines:",
            file=sys.stderr,
        )
        for line in tail[-15:]:
            print(f"  {line}", file=sys.stderr)
        return 1
    print(
        f"slurm-monitor bootstrap: {agent_dir} on {target} ready ({elapsed:.0f}s)", file=sys.stderr
    )
    return 0
